services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: phonebook-nginx-prod
    depends_on:
      - backend # wait for the frontend container to be started
      - frontend
  backend:
    image: phonebook-backend-prod
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend/:/usr/src/app
  frontend:
    image: phonebook-frontend-prod
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules