services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: phonebook-nginx
    depends_on:
      - backend # wait for the frontend container to be started
      - frontend
  backend:
    image: phonebook-backend-dev
    build:
      context: ./backend/
      dockerfile: ./backend/dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
  frontend:
    image: phonebook-frontend-dev
    build:
      context: ./frontend/
      dockerfile: ./frontend/dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules