services:
  app:
    image: todo-frontend-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    ports:
      - 5173:5173
    environment:
      VITE_BACKEND_URL: http://localhost:3000/
    volumes: 
      - ./:/usr/src/app/
    container_name: todo-frontend-dev-container